language: python

python:
  - "3.4"

script:
 - python manage.py makemigrations snippets
 - python manage.py migrate
 - python manage.py runserver
 - curl http://127.0.0.1:8000/ &
 - curl -s -o /dev/null -w "%{http_code}" http://127.0.0.1:8000/

