language: python

python:
  - "3.4"

install:
 - pip install -r requirements.txt

script:
 - python manage.py makemigrations snippets
 - python manage.py migrate
 - python manage.py runserver
 - python manage.py test
 #- nohup curl http://127.0.0.1:8000/ > /dev/null 2>&1 &
 #- curl -s -o /dev/null -w "%{http_code}" http://127.0.0.1:8000/

