language: python

python:
  - "3.4"

install:
 - pip install -r requirements.txt

script:
 - python manage.py makemigrations snippets
 - python manage.py migrate
 #- nohup python manage.py runserver > /dev/null 2>&1 &
 - python manage.py test
 #- curl http://127.0.0.1:8000/
 #- curl -s -o /dev/null -w "%{http_code}" http://127.0.0.1:8000/

